Backport 3c60f0b2bb75150d49da9ab94d88b767275de5e2
openjdk/jdk21u-dev pull request #1222
Opened 2024-12-11 17:24 UTC by krk

Ref. https://github.com/openjdk/jdk/pull/22479

> We have caught this in some prod environments, where prctl is forbidden by the sandboxing mechanism. This fails the JVM

Backport depends on [JDK-8339063](https://bugs.openjdk.org/browse/) which is included.

JDK-8339063 did not apply cleanly, resolved conflict in `src/hotspot/cpu/aarch64/aarch64.ad` by keeping const qualifiers. These were removed in [JDK-8310948](https://bugs.openjdk.org/browse/JDK-8310948) which doesn't apply cleanly either.

Additional testing:

- [x] Verified the bug is fixed with the seccomp repro from [JDK-8345296](https://bugs.openjdk.org/browse/JDK-8345296?focusedId=14727386&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14727386): Segfault without the patch, works with.

2024-12-11 19:01 UTC, phohensee commented
/issue JDK-8339063

2024-12-11 19:09 UTC, phohensee requested changes
Please add "/issue JDK-8339063" (I'm unsure of the exact syntax, but it's something like that :)), since it's included. Otherwise lgtm.

2024-12-11 19:10 UTC, krk commented
/issue JDK-8339063

2024-12-12 00:38 UTC, phohensee approved these changes

2024-12-12 10:48 UTC, shipilev commented
Seeing the report for Corretto 21 that demonstrates this issue affects some MacOS and Alpine configs:
https://github.com/corretto/corretto-21/issues/85

2024-12-12 11:10 UTC, shipilev commented
I am not entirely convinced the modifications that [JDK-8339063](https://bugs.openjdk.org/browse/JDK-8339063) does to this code are 100% safe. It tries to install the max vector size and exits the VM if not possible? That sounds like a behavioral change with unknown consequences. Looks like we are mixing that backport because we need access to new `FloatRegister` constants? If so, I think it would be safer to just take that particular hunk in `register_aarch64.hpp` only. 

Then if/when we do [JDK-8339063](https://bugs.openjdk.org/browse/JDK-8339063) backport, it would slide right in.

2024-12-12 11:41 UTC, krk commented
Thanks for the details. Yes, it was to access the new `FloatRegister` constants. Simplifying this now.

2024-12-12 13:11 UTC, krk commented
Picked only the necessary hunks from [JDK-8339063](https://bugs.openjdk.org/browse/JDK-8339063).

2024-12-12 13:15 UTC, shipilev commented
Also need `/issue remove JDK-8339063` now?

2024-12-12 13:20 UTC, krk commented
I only included an independeny chunk, not implementing JDK-8339063. It could be independently reviewed.

2024-12-12 13:20 UTC, krk commented
/issue remove JDK-8339063

2024-12-12 13:26 UTC, shipilev approved these changes
This looks correct.

2024-12-12 15:23 UTC, krk commented
/approval request Fix VM crash on production workloads when prctl is disallowed, on AArch64 with SVE.

2024-12-12 21:00 UTC, mrserb commented
@GoeLin We should consider fixing this bug in the upcoming January 2025 release. Jvm crash on different platforms, tested Alpine, AL2, AL2023, macOS 15.2+docker.
@shipilev please confirm

2024-12-13 08:21 UTC, shipilev commented
> @GoeLin We should consider fixing this bug in the upcoming January 2025 release. Jvm crash on different platforms, tested Alpine, AL2, AL2023, macOS 15.2+docker. @shipilev please confirm

Yes, we are planning to pick this fix in Corretto release for January. I think this patch is beneficial to have in all January releases as well. This is ultimately 21u and 17u maintainers' call.

2024-12-13 10:19 UTC, jerboaa commented
/approve yes

Since this is related to prctl returning `-1` in some Docker environments on newer MacOS 15.2+. It does not seem reproducible on native Aarch64 Linux or MacOSX 15.2 and there is a work-around, `-XX:+UseSVE=0`, lets keep this on the April schedule for now. It should be a safe change, but I don't see the urgency either.

2024-12-13 12:12 UTC, krk commented
/sponsor

2024-12-13 12:25 UTC, krk commented
/integrate

2024-12-13 12:36 UTC, closed without merging

2024-12-16 00:23 UTC, lprimak commented
Hi @shipilev @krk 

Looking a bit further into this, I do not understand what the "root cause" of this issue is.
Is this PR a workaround?
For example, running on any Arm machines I have access to (Mac, Graviton Linux, etc.) I cannot get the
`-XX:UseSVE=1` to actually work.

What architecture does this support currently, if any?
It doesn't work on Mac M4, Mac M1, and under VM in Mac M1 or M4, etc.
Is the root cause somewhere in MacOS? If it is, I can't find one.

Thank you

2024-12-16 10:38 UTC, shipilev commented
> Looking a bit further into this, I do not understand what the "root cause" of this issue is. Is this PR a workaround? 

This fix makes sure VM does not crash if lower layer (whether native OS or whatever sandbox/virtualization layer) does not allow us to execute `prctl(PR_SVE_GET_VL)` to get SVE vector length. Whether this is a fix or a workaround depends on whether prohibiting `prctl(PR_SVE_GET_VL)` is a bug or not from the lower layer perspective :) I tend to think the innocuous `prctl`-s should be enabled, so I tend to think about this fix as the workaround.

> What architecture does this support currently, if any? It doesn't work on Mac M4, Mac M1, and under VM in Mac M1 or M4, etc. Is the root cause somewhere in MacOS? If it is, I can't find one.

By "this" you mean SVE? SVE is a feature of modern AArch64 CPUs. AFAIU, this means Apple M4+, Graviton 3+, etc.

2024-12-16 14:53 UTC, lprimak commented
Ok. I think I get it now. 
the only machine with SVE I have access to is M4 Mac. My Graviton machines are G1 so they wouldn’t work. 

So the root cause is that Sonoma 15.2 introduced a regression that breaks SVE. 
it makes it unavailable natively and crashes JVM under a virtualization environments 

thank you.