8335283: Build failure due to 'no_sanitize' attribute directive ignored
openjdk/jdk21u-dev pull request #828
Opened 2024-07-08 06:55 UTC by luwang1103

Hi all，
This pull request contains a backport of commit [53242cdf](https://github.com/openjdk/jdk/commit/53242cdf9ef17c502ebd541e84370e7c158639c1) from the [master](https://github.com/openjdk/jdk) repository.

The commit being backported was authored by Matthias Baesken on 1 July 2024.

Thanks！

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] [JDK-8335283](https://bugs.openjdk.org/browse/JDK-8335283) needs maintainer approval

### Issue
 * [JDK-8335283](https://bugs.openjdk.org/browse/JDK-8335283): Build failure due to 'no_sanitize' attribute directive ignored (**Bug** - P3)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/828/head:pull/828` \
`$ git checkout pull/828`

Update a local copy of the PR: \
`$ git checkout pull/828` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/828/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 828`

View PR using the GUI difftool: \
`$ git pr show -t 828`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/828.diff">https://git.openjdk.org/jdk21u-dev/pull/828.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/828#issuecomment-2213223312)

2024-07-08 10:15 UTC, shipilev commented
Hey @luwang1103, this is not how one does a backport, as bots warn in PR body. I think you can make it a backport PR by changing the PR title to `Backport 53242cdf9ef17c502ebd541e84370e7c158639c1`

2024-07-09 09:50 UTC, shipilev requested changes
No, wait, this is not what the original change did: https://github.com/openjdk/jdk/commit/53242cdf9ef17c502ebd541e84370e7c158639c1

I think it would be much cleaner to backport [JDK-8334239](https://bugs.openjdk.org/browse/JDK-8334239) first.

2024-07-10 01:32 UTC, luwang1103 commented
> No, wait, this is not what the original change did: [openjdk/jdk@53242cd](https://github.com/openjdk/jdk/commit/53242cdf9ef17c502ebd541e84370e7c158639c1)不，等等，这不是最初的更改：[openjdk/jdk@53242cd](https://github.com/openjdk/jdk/commit/53242cdf9ef17c502ebd541e84370e7c158639c1)
> 
> I think it would be much cleaner to backport [JDK-8334239](https://bugs.openjdk.org/browse/JDK-8334239) first.我认为首先将[JDK-8334239](https://bugs.openjdk.org/browse/JDK-8334239)反向移植会更干净。

ohhhhhh,This is something I didn't notice. I will modify it to the correct one. Thank you for your help.

2024-07-10 08:29 UTC, shipilev commented
Let's just backport [JDK-8334239](https://bugs.openjdk.org/browse/JDK-8334239) separately, and then get back to this one. Currently, it is confusing what this backport PR actually does.

2024-07-10 09:06 UTC, luwang1103 commented
> Let's just backport [JDK-8334239](https://bugs.openjdk.org/browse/JDK-8334239) separately, and then get back to this one. Currently, it is confusing what this backport PR actually does.

I'm not sure what you mean.What should I do next?

2024-07-10 09:13 UTC, luwang1103 commented
> > I'm not sure what you mean.What should I do next?
> 
> Create a standalone PR for [JDK-8334239](https://bugs.openjdk.org/browse/JDK-8334239) backport and work through than one first, then get back to this PR, which should then be clean.

okkkkk,thank you! have a good day.

2024-07-22 08:21 UTC, shipilev commented
@luwang1103 -- I think it would be better to pick up the original changeset into this PR and force-push. It should then be clean?

2024-07-23 09:28 UTC, closed without merging